name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install --no-frozen-lockfile

      - name: Build
        run: npm run build

      - name: Cache dist
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          retention-days: 3
          name: dist
          path: dist

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install --no-frozen-lockfile

      - name: Restore dist cache
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: dist
          path: dist

      - name: Run tests
        run: npm run test
