name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install --no-frozen-lockfile

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

